<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
#importando a lib
import numpy as np

In [44]:
#criando uma array - nome_da_Array = np.array([elemento1, elemento2, ..., elementon])
arr1 = np.array([1, 2, 3])
#printando essa array
arr1

array([1, 2, 3])

In [45]:
#tipo da array? temos. basta usar a função type, passando o parâmetro, a própria array.
type(arr1)

numpy.ndarray

In [46]:
#array de 2 dimensões? temos também. só criar agora:
arr2 = np.array([[1,2,3],[4,5,6]])
#printa a array
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
type(arr2)

numpy.ndarray

In [48]:
#  acessar os elementos:
#quem tá na posição 0 da minha array arr1? só printa assim:
arr1[0]

1

In [49]:
##  acessar os elementos:
# matriz - lista de listas
arr2[1][1] #linha 1, elemento 1, consegue ver?


5

In [50]:
#criar uma array passando a posição inicial e a final, ou seja, onde vai começar e onde vai terminar.
# para isso, a gente utiliza a arange dentro da numpy.
arr3 = np.arange(0,9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
#também dá pra criar arrays de "pulinhos em pulinhos", ou seja, espaçamento entre os números, utilizando a arange:
arr4 = np.arange(0,9,3)
arr4
#np.arange(posiçao_inicial, posição_final, pulinhos)

array([0, 3, 6])

In [52]:
# matriz de 1 dimensão que contém só zeros:
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
# matriz de 2 dimensões que contém só zeros:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
# matriz de 1 dimensão que contém só 1's
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [55]:
#matriz de 2 dimensões que contém só 1's
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [56]:
#matriz identidade --> eye
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [57]:
# matriz de números aleatórios de 0 a 1
arr5 = np.random.rand(6)
arr5

array([0.30284839, 0.94788288, 0.86757267, 0.38833325, 0.62704087,
       0.08958586])

In [58]:
#uma espécie de sorteio?
np.random.randint(6)
#np.random.randint(tamanho_do_intervalo) --> retorna um valor inteiro dentro do tamanho desse intervalo

3

In [59]:
#retorna uma matriz (de acordo com o shape passado) de valores inteiros dentro do intervalo passado
# np.random.randint (menor_posição, maior_posição, (shape))
np.random.randint(5, 36, (2,3))

array([[21, 11, 24],
       [13, 35,  5]])

In [60]:
#matriz de 3 dimensões:
np.random.randint(6, 58, (5, 9, 2))

array([[[20, 32],
        [42, 17],
        [34, 24],
        [21, 16],
        [25,  7],
        [22, 31],
        [12, 35],
        [46, 36],
        [10, 14]],

       [[10, 55],
        [25, 17],
        [14, 53],
        [21, 13],
        [17, 31],
        [14, 19],
        [53, 13],
        [46, 57],
        [29, 43]],

       [[38, 37],
        [51, 37],
        [46, 12],
        [14, 42],
        [52, 38],
        [13, 31],
        [14, 21],
        [53, 54],
        [41, 10]],

       [[11, 18],
        [49, 34],
        [43, 41],
        [20, 17],
        [32, 27],
        [16, 31],
        [15, 47],
        [14, 42],
        [30, 18]],

       [[29, 48],
        [55, 29],
        [27, 43],
        [25, 25],
        [12, 29],
        [53, 22],
        [ 9, 22],
        [21, 40],
        [55, 14]]])

In [61]:
# pega um número aleatório double, digamos assim, entre 5 e 9
np.random.uniform(5, 9)

8.658842777571621

In [62]:
# mesma coisa do np.random.randint, só que tem uma diferença: o número não é inteiro (podemos chamar de double)
np.random.uniform(6, 9, (5, 8))

array([[7.32584219, 7.72024056, 8.28786659, 7.02063909, 6.89629235,
        7.73860933, 8.26886346, 6.08577282],
       [7.1787892 , 6.8693944 , 8.48126994, 7.01965544, 8.78005256,
        6.88135642, 6.91787907, 7.89694959],
       [6.71745099, 7.48462225, 7.77205679, 7.81081893, 8.84800737,
        6.46037448, 8.17307986, 6.74244634],
       [8.73624145, 7.77805063, 7.95221653, 6.31406944, 7.13770968,
        7.77345176, 8.20436585, 7.9796427 ],
       [8.15020658, 6.2759605 , 6.54247532, 6.78184706, 6.33709108,
        8.30580799, 8.83419375, 7.55102989]])

In [63]:
# Parâmetros : size int ou tupla de ints, opcional
# Desenhe amostras de uma distribuição Normal padrão (média=0, stdev=1)
# distribuição Normal padrão ---> noções de estátistica 
np.random.standard_normal(5)

array([-1.56609804, -1.39782105,  0.87038128, -0.08448046,  0.44908308])

In [64]:
np.random.standard_normal((3,6))

array([[ 0.35063978, -0.55601786,  1.15788513,  0.00579859,  1.96588891,
         0.52439779],
       [-0.14889514, -0.87983596, -0.0259152 ,  0.93574938, -1.14059574,
         2.00946065],
       [-0.60358725, -1.02169881,  0.31420204, -0.11025119, -1.33448853,
        -1.21848884]])

In [65]:
#mudar o shape de uma matriz:
mat1 = np.random.rand(6)
mat1

array([0.58526913, 0.65628539, 0.29950171, 0.16153222, 0.32848738,
       0.88905122])

In [66]:
# qual o shape da matriz?
mat1.shape

(6,)

In [67]:
# mudei o shape da mat1
mat1.reshape(2,3)

array([[0.58526913, 0.65628539, 0.29950171],
       [0.16153222, 0.32848738, 0.88905122]])

In [68]:
# essa função nos retorna o maior número existente em mat1
mat1.max()

0.8890512238348093

In [69]:
#essa função nos retorna a posição do maior número existente em mat1
mat1.argmax()

5

In [70]:
# media de mat1:
mat1.mean()

0.48668784352992334

In [71]:
mat2 = np.random.rand(6)
mat2

array([0.07178297, 0.97763558, 0.70499036, 0.43667362, 0.95307019,
       0.02223739])

In [72]:
#soma de matrizes: só somar como se fosse uma continha de dois números no papel ---> x+y
mat3 = mat1 + mat2
mat3 

array([0.6570521 , 1.63392097, 1.00449207, 0.59820584, 1.28155758,
       0.91128861])

In [73]:
#multiplicação de matrizes:
mat1 * mat2

array([0.04201236, 0.64160795, 0.21114582, 0.07053686, 0.31307153,
       0.01977018])

In [74]:
# raiz quadrada da matriz:
np.sqrt(mat1)

array([0.76502884, 0.81011443, 0.54726749, 0.40191071, 0.57313819,
       0.94289513])

In [75]:
# raiz cúbica
np.cbrt(mat1)

array([0.8364729 , 0.86902228, 0.66906211, 0.54461098, 0.68998486,
       0.96155824])

In [76]:
mat4 = np.random.rand(1, 6)
mat4

array([[0.97847576, 0.59761942, 0.15402465, 0.3594788 , 0.05129083,
        0.67250656]])

In [77]:
# soma dos elementos da matriz:
mat4.sum()

2.8133960210628954

In [78]:
# desvio padrão dos elementos:
mat4.std()

0.3170721988677839

In [79]:
mat4.shape

(1, 6)

In [80]:
# criar uma outra matriz a partir do reshape de uma:
mat5 = mat4.reshape(6,1)
mat5

array([[0.97847576],
       [0.59761942],
       [0.15402465],
       [0.3594788 ],
       [0.05129083],
       [0.67250656]])

In [81]:
#função que multiplica duas matrizes:
np.matmul(mat5, mat4)

array([[0.9574148 , 0.58475611, 0.15070939, 0.35174129, 0.05018683,
        0.65803137],
       [0.58475611, 0.35714897, 0.09204812, 0.21483151, 0.0306524 ,
        0.40190298],
       [0.15070939, 0.09204812, 0.02372359, 0.0553686 , 0.00790005,
        0.10358259],
       [0.35174129, 0.21483151, 0.0553686 , 0.12922501, 0.01843797,
        0.24175185],
       [0.05018683, 0.0306524 , 0.00790005, 0.01843797, 0.00263075,
        0.03449342],
       [0.65803137, 0.40190298, 0.10358259, 0.24175185, 0.03449342,
        0.45226508]])

In [86]:
mat6 = np.random.rand(2,3)
mat6

array([[0.26383373, 0.42015684, 0.7608746 ],
       [0.62836323, 0.2364423 , 0.54215993]])

In [87]:
#soma por eixo:
#axis=0 é linha, ou seja, as linhas tem seus valores somados.
mat6.sum(axis=0)

array([0.89219697, 0.65659914, 1.30303453])

In [88]:
#axis=1 - coluna
mat6.sum(axis=1)

array([1.44486517, 1.40696546])

In [ ]:
#1:02:20 - continuar