<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
#importando a lib
import numpy as np

In [59]:
#criando uma array - nome_da_Array = np.array([elemento1, elemento2, ..., elementon])
arr1 = np.array([1, 2, 3])
#printando essa array
arr1

array([1, 2, 3])

In [60]:
#tipo da array? temos. basta usar a função type, passando o parâmetro, a própria array.
type(arr1)

numpy.ndarray

In [61]:
#array de 2 dimensões? temos também. só criar agora:
arr2 = np.array([[1,2,3],[4,5,6]])
#printa a array
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
type(arr2)

numpy.ndarray

In [63]:
#  acessar os elementos:
#quem tá na posição 0 da minha array arr1? só printa assim:
arr1[0]

1

In [64]:
##  acessar os elementos:
# matriz - lista de listas
arr2[1][1] #linha 1, elemento 1, consegue ver?


5

In [65]:
#criar uma array passando a posição inicial e a final, ou seja, onde vai começar e onde vai terminar.
# para isso, a gente utiliza a arange dentro da numpy.
arr3 = np.arange(0,9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
#também dá pra criar arrays de "pulinhos em pulinhos", ou seja, espaçamento entre os números, utilizando a arange:
arr4 = np.arange(0,9,3)
arr4
#np.arange(posiçao_inicial, posição_final, pulinhos)

array([0, 3, 6])

In [67]:
# matriz de 1 dimensão que contém só zeros:
np.zeros(4)

array([0., 0., 0., 0.])

In [68]:
# matriz de 2 dimensões que contém só zeros:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# matriz de 1 dimensão que contém só 1's
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [72]:
#matriz de 2 dimensões que contém só 1's
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [73]:
#matriz identidade --> eye
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [74]:
# matriz de números aleatórios de 0 a 1
arr5 = np.random.rand(6)
arr5

array([0.01363464, 0.56462775, 0.70458393, 0.07761108, 0.94369824,
       0.97050398])

In [75]:
#uma espécie de sorteio?
np.random.randint(6)
#np.random.randint(tamanho_do_intervalo) --> retorna um valor inteiro dentro do tamanho desse intervalo

2

In [76]:
#retorna uma matriz (de acordo com o shape passado) de valores inteiros dentro do intervalo passado
# np.random.randint (menor_posição, maior_posição, (shape))
np.random.randint(5, 36, (2,3))

array([[16, 22, 19],
       [14, 32, 33]])

In [79]:
#matriz de 3 dimensões:
np.random.randint(6, 58, (5, 9, 2))

array([[[45, 56],
        [16, 14],
        [ 9, 32],
        [16, 28],
        [23, 14],
        [42, 14],
        [49, 40],
        [48, 19],
        [12, 48]],

       [[26, 30],
        [21, 25],
        [40, 11],
        [26, 55],
        [41, 55],
        [50, 29],
        [12, 13],
        [50, 27],
        [53, 32]],

       [[57, 20],
        [53, 46],
        [32, 41],
        [39, 42],
        [24,  6],
        [25, 27],
        [39, 10],
        [43, 12],
        [39, 26]],

       [[40, 31],
        [54, 18],
        [48, 40],
        [36, 57],
        [30, 20],
        [20, 39],
        [48, 54],
        [ 8, 21],
        [53, 36]],

       [[27, 20],
        [42, 24],
        [49, 44],
        [23, 47],
        [23, 47],
        [49, 39],
        [49, 24],
        [29,  6],
        [23, 12]]])

In [81]:
# pega um número aleatório double, digamos assim, entre 5 e 9
np.random.uniform(5, 9)

6.601192250529586

In [82]:
# mesma coisa do np.random.randint, só que tem uma diferença: o número não é inteiro (podemos chamar de double)
np.random.uniform(6, 9, (5, 8))

array([[7.36664127, 6.77501712, 6.0592906 , 7.69318839, 8.9823072 ,
        6.42143879, 6.70009741, 7.62605068],
       [8.62242948, 7.88827103, 8.33350609, 7.13486325, 7.64624105,
        8.37825541, 7.21992401, 8.60050079],
       [8.27195732, 8.31214145, 8.43919249, 8.32680101, 8.66927293,
        7.86203694, 6.47577071, 7.09137319],
       [8.64289276, 6.25411172, 7.65235403, 6.57958655, 7.13741095,
        7.97620038, 7.45714634, 6.56398935],
       [6.21613522, 6.2440552 , 7.71596494, 6.69331191, 7.57031066,
        7.55289955, 7.66623582, 7.82370093]])

In [83]:
# Parâmetros : size int ou tupla de ints, opcional
# Desenhe amostras de uma distribuição Normal padrão (média=0, stdev=1)
# distribuição Normal padrão ---> noções de estátistica 
np.random.standard_normal(5)

array([-0.93163246,  0.18124262, -0.54080318, -1.23967942, -0.74930405])

In [84]:
np.random.standard_normal((3,6))

array([[ 0.85950739,  2.04519184,  0.05059185, -0.22889716,  0.22880006,
         1.05475989],
       [ 1.39222438,  0.10714605, -0.0255169 ,  0.61740744,  1.93102333,
        -0.46046291],
       [ 0.32218919, -0.11943847,  0.83955098, -1.13635797,  0.17236095,
         0.06059814]])

In [85]:
#mudar o shape de uma matriz:
mat1 = np.random.rand(6)
mat1

array([0.79654121, 0.72857771, 0.40911832, 0.52964148, 0.55182329,
       0.62925259])

In [86]:
# qual o shape da matriz?
mat1.shape

(6,)

In [87]:
# mudei o shape da mat1
mat1.reshape(2,3)

array([[0.79654121, 0.72857771, 0.40911832],
       [0.52964148, 0.55182329, 0.62925259]])

In [88]:
# essa função nos retorna o maior número existente em mat1
mat1.max()

0.7965412127895479

In [89]:
#essa função nos retorna a posição do maior número existente em mat1
mat1.argmax()

0

In [90]:
# media de mat1:
mat1.mean()

0.607492433155013

In [91]:
mat2 = np.random.rand(6)
mat2

array([0.83352651, 0.99052235, 0.62179866, 0.57980795, 0.22322003,
       0.23726291])

In [92]:
#soma de matrizes: só somar como se fosse uma continha de dois números no papel ---> x+y
mat3 = mat1 + mat2
mat3 

array([1.63006772, 1.71910006, 1.03091697, 1.10944943, 0.77504332,
       0.8665155 ])

In [93]:
#multiplicação de matrizes:
mat1 * mat2

array([0.66393822, 0.72167251, 0.25438922, 0.30709034, 0.12317801,
       0.1492983 ])

In [94]:
# raiz quadrada da matriz:
np.sqrt(mat1)

array([0.89249158, 0.85356764, 0.63962357, 0.72776471, 0.74284809,
       0.79325443])

In [95]:
# raiz cúbica
np.cbrt(mat1)

array([0.92697798, 0.89982618, 0.74236298, 0.80908471, 0.82022564,
       0.85692275])

In [96]:
mat4 = np.random.rand(1, 6)
mat4

array([[0.95081588, 0.15225673, 0.82985968, 0.28000193, 0.73964652,
        0.39170708]])

In [97]:
# soma dos elementos da matriz:
mat4.sum()

3.3442878195503782

In [98]:
# desvio padrão dos elementos:
mat4.std()

0.29742478642704934

In [99]:
mat4.shape

(1, 6)

In [100]:
# criar uma outra matriz a partir do reshape de uma:
mat5 = mat4.reshape(6,1)
mat5

array([[0.95081588],
       [0.15225673],
       [0.82985968],
       [0.28000193],
       [0.73964652],
       [0.39170708]])

In [101]:
#função que multiplica duas matrizes:
np.matmul(mat5, mat4)

array([[0.90405083, 0.14476812, 0.78904376, 0.26623028, 0.70326766,
        0.37244131],
       [0.14476812, 0.02318211, 0.12635172, 0.04263218, 0.11261616,
        0.05964004],
       [0.78904376, 0.12635172, 0.68866708, 0.23236231, 0.61380283,
        0.32506191],
       [0.26623028, 0.04263218, 0.23236231, 0.07840108, 0.20710246,
        0.10967874],
       [0.70326766, 0.11261616, 0.61380283, 0.20710246, 0.54707698,
        0.28972478],
       [0.37244131, 0.05964004, 0.32506191, 0.10967874, 0.28972478,
        0.15343444]])

In [102]:
#continuar em 58:45