<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importando a lib
import numpy as np

In [ ]:
#criando uma array - nome_da_Array = np.array([elemento1, elemento2, ..., elementon])
arr1 = np.array([1, 2, 3])
#printando essa array
arr1

array([1, 2, 3])

In [ ]:
#tipo da array? temos. basta usar a função type, passando o parâmetro, a própria array.
type(arr1)

numpy.ndarray

In [ ]:
#array de 2 dimensões? temos também. só criar agora:
arr2 = np.array([[1,2,3],[4,5,6]])
#printa a array
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
#  acessar os elementos:
#quem tá na posição 0 da minha array arr1? só printa assim:
arr1[0]

1

In [ ]:
##  acessar os elementos:
# matriz - lista de listas
arr2[1][1] #linha 1, elemento 1, consegue ver?


5

In [ ]:
#criar uma array passando a posição inicial e a final, ou seja, onde vai começar e onde vai terminar.
# para isso, a gente utiliza a arange dentro da numpy.
arr3 = np.arange(0,9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#também dá pra criar arrays de "pulinhos em pulinhos", ou seja, espaçamento entre os números, utilizando a arange:
arr4 = np.arange(0,9,3)
arr4
#np.arange(posiçao_inicial, posição_final, pulinhos)

array([0, 3, 6])

In [ ]:
# matriz de 1 dimensão que contém só zeros:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
# matriz de 2 dimensões que contém só zeros:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# matriz de 1 dimensão que contém só 1's
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#matriz de 2 dimensões que contém só 1's
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#matriz identidade --> eye
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
# matriz de números aleatórios de 0 a 1
arr5 = np.random.rand(6)
arr5

array([0.32975302, 0.28226836, 0.94996084, 0.78131679, 0.03384206,
       0.69001139])

In [ ]:
#uma espécie de sorteio?
np.random.randint(6)
#np.random.randint(tamanho_do_intervalo) --> retorna um valor inteiro dentro do tamanho desse intervalo

4

In [ ]:
#retorna uma matriz (de acordo com o shape passado) de valores inteiros dentro do intervalo passado
# np.random.randint (menor_posição, maior_posição, (shape))
np.random.randint(5, 36, (2,3))

array([[25, 10,  5],
       [22, 15, 13]])

In [ ]:
#matriz de 3 dimensões:
np.random.randint(6, 58, (5, 9, 2))

array([[[42, 44],
        [21, 15],
        [12, 40],
        [29, 41],
        [54, 19],
        [22, 44],
        [41, 22],
        [16, 55],
        [15, 45]],

       [[34, 56],
        [45, 43],
        [11, 28],
        [11, 31],
        [37, 34],
        [23, 28],
        [40, 19],
        [47, 30],
        [40, 51]],

       [[27, 34],
        [40, 45],
        [ 9, 48],
        [41, 39],
        [48, 37],
        [15, 24],
        [36, 14],
        [45, 26],
        [49, 31]],

       [[12,  8],
        [23, 26],
        [44, 20],
        [26, 38],
        [14, 35],
        [33, 52],
        [26, 23],
        [ 7, 31],
        [36, 12]],

       [[57, 40],
        [14, 54],
        [55, 51],
        [41, 12],
        [48,  8],
        [41, 38],
        [50, 52],
        [43, 30],
        [33, 20]]])

In [ ]:
# pega um número aleatório double, digamos assim, entre 5 e 9
np.random.uniform(5, 9)

7.063188912279433

In [ ]:
# mesma coisa do np.random.randint, só que tem uma diferença: o número não é inteiro (podemos chamar de double)
np.random.uniform(6, 9, (5, 8))

array([[6.54788414, 7.36450539, 6.81210156, 6.29883047, 8.38728698,
        7.79584893, 6.15394467, 7.42841798],
       [7.64773529, 8.80954074, 6.3519966 , 6.59222281, 7.2157048 ,
        8.71521887, 7.95910146, 6.59475392],
       [8.89930981, 8.59460891, 8.11609293, 8.71028409, 8.6591416 ,
        7.91326715, 7.84076565, 8.9340684 ],
       [8.14954389, 7.3237289 , 6.11407335, 7.251745  , 6.77205957,
        6.4777259 , 6.54143112, 6.77824595],
       [7.69502046, 6.51362724, 6.94839636, 6.93846953, 6.05340201,
        7.95789583, 6.72344726, 6.51135104]])

In [ ]:
# Parâmetros : size int ou tupla de ints, opcional
# Desenhe amostras de uma distribuição Normal padrão (média=0, stdev=1)
# distribuição Normal padrão ---> noções de estátistica 
np.random.standard_normal(5)

array([-0.19536295,  1.13307789, -1.55951509,  0.4429637 ,  1.64951052])

In [ ]:
np.random.standard_normal((3,6))

array([[-0.56602789,  0.75953946, -0.04507521,  1.30284285, -0.77753667,
        -0.57674566],
       [ 0.42160829, -0.04393227, -0.55318814,  2.68389655, -1.88935569,
        -0.29824662],
       [-0.2417632 , -0.57314667,  1.42119329,  0.46770359,  1.93642027,
         0.37428126]])

In [ ]:
#mudar o shape de uma matriz:
mat1 = np.random.rand(6)
mat1

array([0.95670645, 0.92913066, 0.89081776, 0.15854283, 0.52470912,
       0.22581573])

In [ ]:
# qual o shape da matriz?
mat1.shape

(6,)

In [ ]:
# mudei o shape da mat1
mat1.reshape(2,3)

array([[0.95670645, 0.92913066, 0.89081776],
       [0.15854283, 0.52470912, 0.22581573]])

In [ ]:
#continuarf em 34:38 da lecture3