<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/C%C3%B3pia_de_Lista_Vivi_Python_Basics_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Questionário de casa - Python & Numpy

### Faça uma cópia deste notebook para o seu drive e responda às perguntas

In [1]:
import numpy as np

### (15 pontos) Questão 1. Considere uma lista de tamanho 6, onde cada elemento "i" representa um grupo de funcionários situados numa faixa salarial. Na descrição abaixo você encontra a faixa salarial associada a cada elemento "i" da lista.

<ol start="0">
<li> Funcionários com 1,2k ≤ salário ≤ 2,5k </li>
<li> Funcionários com 2,5k < salário ≤ 3,5k </li>
<li> Funcionários com 3,5k < salário ≤ 4,5k </li>
<li> Funcionários com 4,5k < salário ≤ 5,5k </li>
<li> Funcionários com 5,5k < salário ≤ 6,5k </li>
<li> Funcionários com 6,5k < salário ≤ 7,5k </li>
</ol>

##### Inicialmente, a quantidade de funcionários contratados pela empresa é zero em cada faixa salarial. Por este motivo, a lista "funcionarios_candidatos" possui apenas zero no começo do programa. Com o passar do tempo a empresa foi contratando novos funcionarios, expressos no dicionário "novos_funcionarios"

##### **Faça um loop percorrendo todos os funcionários candidatos da variável "funcionarios_candidatos" e incremente os valores da lista "funcionarios_contratados" conforme a faixa salarial dos novos contratados. Em seguida, exiba:**

<ol type="A">
<li> (3.75 pontos) A quantidade de funcionários 2,5k < salário ≤ 5,5k  </li>
<li> (3.75 pontos) A quantidade de funcionários 4,5k < salário ≤ 6,5k  </li>
<li> (3.75 pontos) A quantidade de funcionários 3,5k < salário ≤ 7,5k  </li>
<li> (3.75 pontos) A quantidade de funcionários 1,2k < salário ≤ 3,5k ou 4,5k < salário ≤ 6,5k </li>
</ol>

In [3]:
funcionarios_candidatos = [0, 0, 0, 0, 0, 0]
novos_funcionarios = {
    "candidato_0": {"salario": 3600, "nome": "Anaximandro"},
    "candidato_1": {"salario": 5200, "nome": "Eurípedes"},
    "candidato_2": {"salario": 2300, "nome": "Sófocles"},
    "candidato_3": {"salario": 1240, "nome": "Górgias"},
    "candidato_4": {"salario": 7000, "nome": "Messala"},
    "candidato_5": {"salario": 6700, "nome": "Aristófanes"},
    "candidato_6": {"salario": 4000, "nome": "Clístenes"},
    "candidato_7": {"salario": 4500, "nome": "Misandro"},
    "candidato_8": {"salario": 3000, "nome": "Ajax Telamônio"}
}

In [4]:
for candidato, info in novos_funcionarios.items():
    salario = info["salario"]

    if 2500 < salario <= 5500:
        funcionarios_candidatos[0] += 1
    if 4500 < salario <= 6500:
        funcionarios_candidatos[1] += 1
    if 3500 < salario <= 7500:
        funcionarios_candidatos[2] += 1
    if (1200 < salario <= 3500) or (4500 < salario <= 6500):
        funcionarios_candidatos[3] += 1

In [5]:
# solução A.
print(f'A. Quantidade de funcionários 2,5k < salário ≤ 5,5k: {funcionarios_candidatos[0]}')

A. Quantidade de funcionários 2,5k < salário ≤ 5,5k: 5


In [6]:
# solução B.
print(f'B. Quantidade de funcionários 4,5k < salário ≤ 6,5k: {funcionarios_candidatos[1]}')

B. Quantidade de funcionários 4,5k < salário ≤ 6,5k: 1


In [7]:
# solução C.
print(f'C. Quantidade de funcionários 3,5k < salário ≤ 7,5k: {funcionarios_candidatos[2]}')

C. Quantidade de funcionários 3,5k < salário ≤ 7,5k: 6


In [10]:
# solução D.
print(f'D. Quantidade de funcionários 1,2k < salário ≤ 3,5k ou 4,5k < salário ≤ 6,5k: {funcionarios_candidatos[3]}')

D. Quantidade de funcionários 1,2k < salário ≤ 3,5k ou 4,5k < salário ≤ 6,5k: 4


### (15 pontos) Questão 2. Considere duas listas, "salario" e "funcionario". Cada elemento "i" da lista "salario" corresponde ao salário do elemento "i" da lista "funcionario". Desse modo, o salario[3] é a representa a remuneração do funcionario[3]. Nesse sentido, faça um código em Python para exibir:

<ol type="A">
<li> (3 pontos) Os dados dos funcionários ordenados pelo salário, do menos para o mais remunerado </li>
<li> (3 pontos) Os dados dos funcionários que possuem 4k ≤ salário ≤ 7k </li>
<li> (3 pontos) Os dados dos funcionários que possuem 4k ≤ salário ≤ 7k ou 5k ≤ salário ≤ 8k </li>
<li> (3 pontos) Os nomes dos funcionários do item C. </li>
<li> (3 pontos) As idades dos funcionários do item C. </li>
</ol>

In [28]:
salario = [2707, 2708, 2967, 7793, 5005, 5206, 4849, 6134, 8175, 7271]
funcionario = [
    {"nome": "Dolão", "idade": 34},
    {"nome": "Príamo", "idade": 72},
    {"nome": "Andrômaca", "idade": 95},
    {"nome": "Aquiles", "idade": 18},
    {"nome": "Agamemnon", "idade": 51},
    {"nome": "Ajax Telamônio", "idade": 41},
    {"nome": "Menelau", "idade": 54},
    {"nome": "Nestor",  "idade": 67},
    {"nome": "Cassandra", "idade": 39},
    {"nome": "Pátroclo", "idade": 22}
]

In [29]:
# solução A.
dados_ordenados = sorted(zip(salario, funcionario), key=lambda x: x[0])

print("A. Dados dos funcionários ordenados pelo salário:")
for salario, func in dados_ordenados:
    print(f"Nome: {func['nome']}, Salário: {salario}, Idade: {func['idade']}")



A. Dados dos funcionários ordenados pelo salário:
Nome: Dolão, Salário: 2707, Idade: 34
Nome: Príamo, Salário: 2708, Idade: 72
Nome: Andrômaca, Salário: 2967, Idade: 95
Nome: Menelau, Salário: 4849, Idade: 54
Nome: Agamemnon, Salário: 5005, Idade: 51
Nome: Ajax Telamônio, Salário: 5206, Idade: 41
Nome: Nestor, Salário: 6134, Idade: 67
Nome: Pátroclo, Salário: 7271, Idade: 22
Nome: Aquiles, Salário: 7793, Idade: 18
Nome: Cassandra, Salário: 8175, Idade: 39


In [40]:
# solução B.
print("\nB. Dados dos funcionários com 4k ≤ salário ≤ 7k:")
for sal, func in dados_ordenados:
    if 4000 <= sal <= 7000:
        print(f"Nome: {func['nome']}, Salário: {sal}, Idade: {func['idade']}")


B. Dados dos funcionários com 4k ≤ salário ≤ 7k:
Nome: Menelau, Salário: 4849, Idade: 54
Nome: Agamemnon, Salário: 5005, Idade: 51
Nome: Ajax Telamônio, Salário: 5206, Idade: 41
Nome: Nestor, Salário: 6134, Idade: 67


In [44]:
# solução C.
print("\nC. Dados dos funcionários com 4k ≤ salário ≤ 7k ou 5k ≤ salário ≤ 8k:")
for salario, func in dados_ordenados:
    if 4000 <= salario <= 7000 or 5000 <= salario <= 8000:
        print(f"Nome: {func['nome']}, Salário: {salario}, Idade: {func['idade']}")


C. Dados dos funcionários com 4k ≤ salário ≤ 7k ou 5k ≤ salário ≤ 8k:
Nome: Menelau, Salário: 4849, Idade: 54
Nome: Agamemnon, Salário: 5005, Idade: 51
Nome: Ajax Telamônio, Salário: 5206, Idade: 41
Nome: Nestor, Salário: 6134, Idade: 67
Nome: Pátroclo, Salário: 7271, Idade: 22
Nome: Aquiles, Salário: 7793, Idade: 18


In [45]:
# solução D.
print("\nD. Nomes dos funcionários do item C:")
for salario, func in dados_ordenados:
    if 4000 <= salario <= 7000 or 5000 <= salario <= 8000:
        print(func['nome'])


D. Nomes dos funcionários do item C:
Menelau
Agamemnon
Ajax Telamônio
Nestor
Pátroclo
Aquiles


In [46]:
# solução E.
print("\nE. Idades dos funcionários do item C:")
for salario, func in dados_ordenados:
    if 4000 <= salario <= 7000 or 5000 <= salario <= 8000:
        print(func['idade'])


E. Idades dos funcionários do item C:
54
51
41
67
22
18


### (16 pontos) Questão 3. Considere a lista "L1". Preencha a lista "L2" de tal modo que cada elemento L2[i] seja igual ao elemento L1[i] substraído da média de "L1", e dividido pelo desvio padrão de "l1". Ou seja, L2[i] = (L1[i] - mean)/std

In [48]:
L1 = np.array([ 4,  7,  5, 10,  7,  3, 11,  2,  6, 10])
L2 = []

In [49]:
# solução da questão

mean = np.mean(L1)
std = np.std(L1)

for i in range(len(L1)):
    L2.append((L1[i] - mean) / std)

print("L2:", L2)

L2: [-0.8500255011475574, 0.17000510022951149, -0.5100153006885344, 1.1900357016065803, 0.17000510022951149, -1.1900357016065803, 1.5300459020656034, -1.5300459020656034, -0.17000510022951149, 1.1900357016065803]


### (27 pontos) Questão 4. A operação de "padding" consiste em preencher os arredores de uma matriz com zeros. Veja o exemplo a seguir.<br>
<hr>
Antes do padding
<table>
<tr>
<td> 1 </td>
<td> 1 </td>
<td> 1 </td>
</tr>
<tr>
<td> 1 </td>
<td> 1 </td>
<td> 1 </td>
</tr>
<tr>
<td> 1 </td>
<td> 1 </td>
<td> 1 </td>
</tr>
</table>
<br>

Depois do padding
<table>
<tr>
<td> 0 </td>
<td> 0 </td>
<td> 0 </td>
<td> 0 </td>
<td> 0 </td>
</tr>
<tr>
<td> 0 </td>
<td> 1 </td>
<td> 1 </td>
<td> 1 </td>
<td> 0 </td>
</tr>
<tr>
<td> 0 </td>
<td> 1 </td>
<td> 1 </td>
<td> 1 </td>
<td> 0 </td>
</tr>
<tr>
<td> 0 </td>
<td> 1 </td>
<td> 1 </td>
<td> 1 </td>
<td> 0 </td>
</tr>
<tr>
<td> 0 </td>
<td> 0 </td>
<td> 0 </td>
<td> 0 </td>
<td> 0 </td>
</tr>
</table>
<br>

Execute as diretivas a seguir:
<ol type="A">
<li> (9 pontos) Crie uma matriz A, de tamanho 3 x 3 preenchida com uns, utilizando numpy </li>
<li> (9 pontos) Crie uma matriz B, de tamanho 5 x 5 preenchida com zeros, utilizando numpy </li>
<li> (9 pontos) Insira os elementos da matriz A na matriz B de modo que a realizar um padding na matriz B. Utilize indexação de matrizes</li>
</ol>

**DICA.: para indexar os elementos de uma matriz 5 x 5, pegando os elementos centrais 3 x 3, faça: M[1:4, 1:4]**


In [ ]:
# solução A.

In [ ]:
# solução B.

In [ ]:
# solução C.

### (27 pontos) Questão 5. O janelamento de uma matriz consiste em percorrer subconjuntos de elementos da mesma matriz de maneira iterativa. Observe o exemplo abaixo.
<hr>
Matriz original

<table>
<tr>
<td> 1 </td>
<td> 2 </td>
<td> 3 </td>
<td> 4 </td>
</tr>
<tr>
<td> 5 </td>
<td> 6 </td>
<td> 7 </td>
<td> 8 </td>
</tr>
<tr>
<td> 9 </td>
<td> 10 </td>
<td> 11 </td>
<td> 12 </td>
</tr>
<tr>
<td> 13 </td>
<td> 14 </td>
<td> 15 </td>
<td> 16 </td>
</tr>
</table>
<br>

Um janelamento 2 x 2 gera o seguinte resultado
<div style="border: 1px solid black">
  <table>
    <tr>
      <td> 1 </td>
      <td> 2 </td>
    </tr>
    <tr>
      <td> 5 </td>
      <td> 6 </td>
    </tr>
  </table>
</div>

<br>
<div style="border: 1px solid black">
  <table>
    <tr>
      <td> 3 </td>
      <td> 4 </td>
    </tr>
    <tr>
      <td> 7 </td>
      <td> 8 </td>
    </tr>
  </table>
</div>

<br>
<div style="border: 1px solid black">
  <table>
    <tr>
      <td> 9 </td>
      <td> 10 </td>
    </tr>
    <tr>
      <td> 13 </td>
      <td> 14 </td>
    </tr>
  </table>
</div>

<br>

<div style="border: 1px solid black">
  <table>
    <tr>
      <td> 11 </td>
      <td> 12 </td>
    </tr>
    <tr>
      <td> 15 </td>
      <td> 16 </td>
    </tr>
  </table>
</div>
<br>

####Utilize indexação de matrizes do numpy para:

<ol type="A">
<li> (9 pontos) Janelar apenas o primeiro quadrado (1, 2, 5, 6). </li>
<li> (9 pontos) Em um loop, janelar todos os quadrados, salvando cada quadrado como elemento de uma lista. Desse modo, você terminará com uma lista de tamanho 4, onde cada elemento L[i] é uma matriz quadrada 2 x 2. </li>
<li> (9 pontos) Tome a lista L do item B., e calcule a média de cada um dos seus elementos </li>
</ol>


In [51]:
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
# solução A.

primeiro_quadrado = matriz[:2, :2]
print("A. Primeiro quadrado:")
print(primeiro_quadrado)


A. Primeiro quadrado:
[[1 2]
 [5 6]]


In [56]:
# solução B.

quadrados_lista = []
for i in range(0, 3, 2):
    for j in range(0, 3, 2):
        quadrado = matriz[i:i+2, j:j+2]
        quadrados_lista.append(quadrado)

quadrados_lista




[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]]),
 array([[ 9, 10],
        [13, 14]]),
 array([[11, 12],
        [15, 16]])]

In [58]:
# solução C.

medias = [np.mean(quadrado) for quadrado in quadrados_lista]

medias

[3.5, 5.5, 11.5, 13.5]