<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importando a lib
import numpy as np

In [2]:
#criando uma array - nome_da_Array = np.array([elemento1, elemento2, ..., elementon])
arr1 = np.array([1, 2, 3])
#printando essa array
arr1

array([1, 2, 3])

In [3]:
#tipo da array? temos. basta usar a função type, passando o parâmetro, a própria array.
type(arr1)

numpy.ndarray

In [4]:
#array de 2 dimensões? temos também. só criar agora:
arr2 = np.array([[1,2,3],[4,5,6]])
#printa a array
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
#  acessar os elementos:
#quem tá na posição 0 da minha array arr1? só printa assim:
arr1[0]

1

In [7]:
##  acessar os elementos:
# matriz - lista de listas
arr2[1][1] #linha 1, elemento 1, consegue ver?


5

In [8]:
#criar uma array passando a posição inicial e a final, ou seja, onde vai começar e onde vai terminar.
# para isso, a gente utiliza a arange dentro da numpy.
arr3 = np.arange(0,9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
#também dá pra criar arrays de "pulinhos em pulinhos", ou seja, espaçamento entre os números, utilizando a arange:
arr4 = np.arange(0,9,3)
arr4
#np.arange(posiçao_inicial, posição_final, pulinhos)

array([0, 3, 6])

In [10]:
# matriz de 1 dimensão que contém só zeros:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
# matriz de 2 dimensões que contém só zeros:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# matriz de 1 dimensão que contém só 1's
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
#matriz de 2 dimensões que contém só 1's
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
#matriz identidade --> eye
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
# matriz de números aleatórios de 0 a 1
arr5 = np.random.rand(6)
arr5

array([0.5525974 , 0.72918085, 0.46770805, 0.89964679, 0.88255191,
       0.95752646])

In [16]:
#uma espécie de sorteio?
np.random.randint(6)
#np.random.randint(tamanho_do_intervalo) --> retorna um valor inteiro dentro do tamanho desse intervalo

4

In [17]:
#retorna uma matriz (de acordo com o shape passado) de valores inteiros dentro do intervalo passado
# np.random.randint (menor_posição, maior_posição, (shape))
np.random.randint(5, 36, (2,3))

array([[30, 27, 20],
       [ 6, 24, 22]])

In [18]:
#matriz de 3 dimensões:
np.random.randint(6, 58, (5, 9, 2))

array([[[20, 39],
        [54, 35],
        [26, 45],
        [29, 57],
        [19, 43],
        [ 9, 24],
        [20, 24],
        [49, 30],
        [33, 56]],

       [[35, 26],
        [16,  8],
        [27, 51],
        [10, 39],
        [ 6, 32],
        [37, 12],
        [23, 26],
        [48, 40],
        [52, 40]],

       [[34, 26],
        [51, 49],
        [32, 57],
        [31, 39],
        [50, 16],
        [48, 48],
        [ 8, 34],
        [24, 49],
        [28, 33]],

       [[16, 39],
        [ 9, 17],
        [35, 28],
        [12, 28],
        [45, 40],
        [25, 27],
        [38,  8],
        [14, 20],
        [39,  8]],

       [[27, 53],
        [50, 44],
        [42, 22],
        [28, 16],
        [19, 14],
        [36, 42],
        [26, 25],
        [37, 41],
        [20, 15]]])

In [19]:
# pega um número aleatório double, digamos assim, entre 5 e 9
np.random.uniform(5, 9)

8.88787547848515

In [20]:
# mesma coisa do np.random.randint, só que tem uma diferença: o número não é inteiro (podemos chamar de double)
np.random.uniform(6, 9, (5, 8))

array([[6.66643107, 6.22076863, 8.92984453, 8.86273935, 6.09980661,
        8.96185915, 7.90855138, 7.21266201],
       [8.46889421, 7.52891358, 7.37893572, 8.46660346, 8.29536883,
        6.09794941, 8.82106689, 8.36936153],
       [8.63007739, 7.51625354, 6.1915573 , 7.42036459, 6.02595001,
        8.82645306, 6.40169738, 8.79264871],
       [8.73823486, 7.15555069, 7.71260011, 6.63914817, 6.25321397,
        7.76571868, 6.25257773, 8.98669031],
       [8.88016671, 7.06327102, 7.15775269, 8.01093053, 6.05349876,
        7.98077618, 8.86542214, 7.04005485]])

In [21]:
# Parâmetros : size int ou tupla de ints, opcional
# Desenhe amostras de uma distribuição Normal padrão (média=0, stdev=1)
# distribuição Normal padrão ---> noções de estátistica 
np.random.standard_normal(5)

array([ 0.17436279, -0.92329247,  0.21434179, -0.38862069,  0.85790504])

In [22]:
np.random.standard_normal((3,6))

array([[-0.70326218,  2.68412986,  0.28547545, -0.74180523, -0.73054181,
        -0.49846561],
       [-0.28591279, -0.49567633,  0.56410274,  0.33605783,  1.42938932,
        -1.97922008],
       [-1.40536396, -0.05370073, -3.08036216, -0.02170432, -0.14432293,
         0.05422306]])

In [23]:
#mudar o shape de uma matriz:
mat1 = np.random.rand(6)
mat1

array([0.44165855, 0.84771615, 0.33701194, 0.24481992, 0.0419728 ,
       0.23618902])

In [24]:
# qual o shape da matriz?
mat1.shape

(6,)

In [25]:
# mudei o shape da mat1
mat1.reshape(2,3)

array([[0.44165855, 0.84771615, 0.33701194],
       [0.24481992, 0.0419728 , 0.23618902]])

In [26]:
# essa função nos retorna o maior número existente em mat1
mat1.max()

0.8477161482809819

In [27]:
#essa função nos retorna a posição do maior número existente em mat1
mat1.argmax()

1

In [28]:
# media de mat1:
mat1.mean()

0.3582280634991896

In [29]:
mat2 = np.random.rand(6)
mat2

array([0.88579811, 0.09336325, 0.03231717, 0.24747956, 0.18418035,
       0.08333538])

In [30]:
#soma de matrizes: só somar como se fosse uma continha de dois números no papel ---> x+y
mat3 = mat1 + mat2
mat3 

array([1.32745666, 0.9410794 , 0.36932911, 0.49229948, 0.22615315,
       0.3195244 ])

In [31]:
#multiplicação de matrizes:
mat1 * mat2

array([0.39122031, 0.07914553, 0.01089127, 0.06058793, 0.00773057,
       0.0196829 ])

In [32]:
# raiz quadrada da matriz:
np.sqrt(mat1)

array([0.66457396, 0.92071502, 0.5805273 , 0.4947928 , 0.20487265,
       0.48599282])

In [33]:
# raiz cúbica
np.cbrt(mat1)

array([0.76154496, 0.94641908, 0.69590255, 0.62557913, 0.34752762,
       0.6181396 ])

In [34]:
mat4 = np.random.rand(1, 6)
mat4

array([[0.29704818, 0.28740201, 0.60327265, 0.91270238, 0.54768567,
        0.99163622]])

In [35]:
# soma dos elementos da matriz:
mat4.sum()

3.6397471075245895

In [36]:
# desvio padrão dos elementos:
mat4.std()

0.27176681507250516

In [37]:
mat4.shape

(1, 6)

In [38]:
# criar uma outra matriz a partir do reshape de uma:
mat5 = mat4.reshape(6,1)
mat5

array([[0.29704818],
       [0.28740201],
       [0.60327265],
       [0.91270238],
       [0.54768567],
       [0.99163622]])

In [39]:
#função que multiplica duas matrizes:
np.matmul(mat5, mat4)

array([[0.08823762, 0.08537224, 0.17920104, 0.27111658, 0.16268903,
        0.29456373],
       [0.08537224, 0.08259992, 0.17338177, 0.2623125 , 0.15740596,
        0.28499824],
       [0.17920104, 0.17338177, 0.3639379 , 0.55060839, 0.33040379,
        0.59822701],
       [0.27111658, 0.2623125 , 0.55060839, 0.83302563, 0.49987401,
        0.90506874],
       [0.16268903, 0.15740596, 0.33040379, 0.49987401, 0.29995959,
        0.54310495],
       [0.29456373, 0.28499824, 0.59822701, 0.90506874, 0.54310495,
        0.98334239]])

In [40]:
mat6 = np.random.rand(2,3)
mat6

array([[0.4649348 , 0.06979375, 0.74970035],
       [0.769574  , 0.15722583, 0.709629  ]])

In [41]:
#soma por eixo:
#axis=0 é linha, ou seja, as linhas tem seus valores somados.
mat6.sum(axis=0)

array([1.2345088 , 0.22701958, 1.45932935])

In [42]:
#axis=1 - coluna
mat6.sum(axis=1)

array([1.2844289 , 1.63642884])

In [45]:
# adicionar uma linha à matriz através da função append:
np.append(mat6, [[6, 8, 9]], axis=0)
#np.append(nome_da_matriz, [linha que quero adicionar], eixo(que é axis=0))

array([[0.4649348 , 0.06979375, 0.74970035],
       [0.769574  , 0.15722583, 0.709629  ],
       [6.        , 8.        , 9.        ]])

In [48]:
mat1

array([0.44165855, 0.84771615, 0.33701194, 0.24481992, 0.0419728 ,
       0.23618902])

In [55]:
#fatiamento da matriz - só botar entre [], separados por : de onde você quer começar e onde você quer terminar
mat1[1:4]

array([0.84771615, 0.33701194, 0.24481992])

In [54]:
#fatiamento da matriz - se você deixar de preencher em algum dos lados do : , ele vai começar do começo ou vai até o final (aqui é entendido isso)
mat1[:3]

array([0.44165855, 0.84771615, 0.33701194])

In [56]:
#fatiamento da matriz - aqui ele foi até o último elemento porque eu deixei em branco.
mat1[3:]

array([0.24481992, 0.0419728 , 0.23618902])

In [69]:
#fatiamento da matriz: tanto de linha, quanto de coluna - Nas linhas, eu peguei tudo. Nas colunas, peguei de 1 atá o final (que é vazio)
mat6[:,1:]

array([[0.06979375, 0.74970035],
       [0.15722583, 0.709629  ]])

In [70]:
mat1

array([0.44165855, 0.84771615, 0.33701194, 0.24481992, 0.0419728 ,
       0.23618902])

In [71]:
#visualização da matriz através de bool - só colocar "True" pra quem você quer que apareça
mat1[[True, False, True, False, True, False]]

array([0.44165855, 0.33701194, 0.0419728 ])

In [72]:
mat1 + 5

array([5.44165855, 5.84771615, 5.33701194, 5.24481992, 5.0419728 ,
       5.23618902])

In [73]:
mat1 > 0.7

array([False,  True, False, False, False, False])

In [74]:
mat1[mat1 > 0.7]

array([0.84771615])

In [75]:
mat6

array([[0.4649348 , 0.06979375, 0.74970035],
       [0.769574  , 0.15722583, 0.709629  ]])

In [76]:
mat6 > 0.25

array([[ True, False,  True],
       [ True, False,  True]])

In [77]:
mat6[mat6 > 0.25]

array([0.4649348 , 0.74970035, 0.769574  , 0.709629  ])