<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/NumPy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**
* Support for large, multi-dimensional arrays
* Mathematical functions to operate on these arrays
* All the values are from the same type
* NumPy arrays use less memory than Python lists
---
## **Colab Shortcuts**
* **CTRL+Space**: Auto complete
* **CTRL+Shift+Space**: Documentation
* **CTRL+Enter**: Run current cell
* **Shift+Enter**: Run current cell and move focus to the next cell (adding one if none exists)
* **Alt+Enter**: Run current cell and insert a new cell below it.
---


## Creating Arrays

In [1]:
#importando a lib, óbvio
import numpy as np

In [2]:
#criar uma array passando a linha logo como parâmetro
# print arryay, só colocando o nome dela
array1 = np.array([2, 4, 1])
array1

array([2, 4, 1])

In [3]:
#quero saber o tipo da array
type(array1) # n-dimensional array

numpy.ndarray

In [4]:
# tipo?
type([2, 4, 1])

list

In [7]:
#criar uma array de 2 rows - dai você só separa as linhas (dentro de colchetes, óbvio) por vírgula ---> 
#np.array(([ar[linha1], [linha2]ray]))
matrix = np.array([[1, 4, 2], [7, 4, 2]])
#print (só colocar o nome e nada mais é obrigatório)
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [8]:
# tipo?
type(matrix)

numpy.ndarray

In [9]:
#mostra a linha 1 da matriz?
#nome_da_matriz[posição]
matrix[1]

array([7, 4, 2])

In [10]:
#quem está na posição 0 da linha 1?
#nome_da_matriz[posição da linha][posição da coluna]
matrix[1][0]

7

In [12]:
# mesma coisa da célula anterior, só que de outro jeitinho
matrix[1, 0]

7

In [13]:
# cria uma matriz através da arange (dai tu passa o ínicio e o fim como parâmetros, lembrando que começa em zero, logo o fim fica n-1)
# matrizNova = np.arange(initial_position, final_position)
array2 = np.arange(1, 10) # array range
#print
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# cria uma array de 5 a 54, espaçado de 5
#np.arange(initial_position, final_position, espaçamento)
np.arange(5, 54, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
#mesma lógica da célula anterior
np.arange(1, 10, 3)

array([1, 4, 7])

In [18]:
#matriz de zeros: 
#matriz_zeros = np.zeros(quantidade)
zeros1d = np.zeros(5)
#print
zeros1d

array([0., 0., 0., 0., 0.])

In [21]:
#matriz de zeros de 2 dimensões
#np.zeros((x,y)) ou np.zeros([x,y])
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#matriz de 1's
#siga a mesma lógica da matriz de zeros
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [23]:
#matriz de zeros de 2 dimensões
#siga a mesma lógica da matriz de zeros
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# cria uma matriz identidade
#np.eye(ordem)
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
# CONTINUAR
arr1 = np.linspace(1, 10, 5)
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(1, 11, 7)

array([ 1.        ,  2.66666667,  4.33333333,  6.        ,  7.66666667,
        9.33333333, 11.        ])

In [ ]:
np.random.rand(5)

array([0.83133248, 0.32052929, 0.33245164, 0.97068504, 0.34096725])

In [ ]:
random_array = np.random.rand(2, 3)
random_array

array([[0.69150385, 0.81882571, 0.95696716],
       [0.87224186, 0.25474342, 0.88008245]])

In [ ]:
np.random.randn(4)

array([ 0.11555967,  1.57133001,  0.68153235, -0.30259484])

In [ ]:
np.random.randint(2, 50)

27

In [ ]:
np.random.randint(2, 50, (4, 2))

array([[44,  3],
       [15,  7],
       [41, 46],
       [ 2, 27]])

In [ ]:
arr1.shape

(5,)

In [ ]:
matrix.shape

(2, 3)

In [ ]:
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [ ]:
matrix.reshape(3, 2) # tem que ter a mesma quantidade de elementos

array([[1, 4],
       [2, 7],
       [4, 2]])

## Operations

In [ ]:
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
arr1.max()

10.0

In [ ]:
arr1.argmax()

4

In [ ]:
arr1.mean()

5.5

In [ ]:
arr1 + 2

array([ 3.  ,  5.25,  7.5 ,  9.75, 12.  ])

In [ ]:
arr1 * 3

array([ 3.  ,  9.75, 16.5 , 23.25, 30.  ])

In [ ]:
arr1 = np.random.randint(2, 50, 5)

In [ ]:
arr2 = np.random.randint(5, 60, 5)

In [ ]:
arr1

array([45, 42, 24,  6, 28])

In [ ]:
arr2

array([52, 45, 44, 21, 14])

In [ ]:
arr1 * arr2

array([2340, 1890, 1056,  126,  392])

In [ ]:
arr1 ** 2

array([2025, 1764,  576,   36,  784])

In [ ]:
np.sqrt(arr1)

array([6.70820393, 6.4807407 , 4.89897949, 2.44948974, 5.29150262])

In [ ]:
np.sum(arr1)

145

In [ ]:
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [ ]:
matrix2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]])
matrix2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
matrix.shape

(2, 3)

In [ ]:
matrix2.shape

(3, 4)

In [ ]:
result = np.matmul(matrix, matrix2)
result

array([[19, 26, 33, 40],
       [25, 38, 51, 64]])

In [ ]:
result.shape

(2, 4)

In [ ]:
arr2d = np.random.randint(1, 100, (4, 5))
arr2d

array([[ 3,  8, 65, 74, 38],
       [78, 39, 65,  9, 81],
       [ 3, 85, 52, 77, 17],
       [ 9, 44,  8, 50, 59]])

In [ ]:
arr2d.sum()

864

In [ ]:
arr2d.sum(axis=0)

array([ 93, 176, 190, 210, 195])

In [ ]:
arr2d.sum(axis=1)

array([188, 272, 234, 170])

## Slices

In [ ]:
arr1

array([45, 42, 24,  6, 28])

In [ ]:
arr1[1:4]

array([42, 24,  6])

In [ ]:
arr1[1:4] = 20

In [ ]:
arr1

array([45, 20, 20, 20, 28])

In [ ]:
arr1[1:4] = np.arange(2, 5)
arr1

array([45,  2,  3,  4, 28])

In [ ]:
matrix = np.random.randint(1, 50, (4, 5))
matrix

array([[29, 42, 34, 29, 38],
       [22, 45, 44, 35, 15],
       [40, 22, 39, 45, 16],
       [ 7, 13, 36, 34,  9]])

In [ ]:
matrix[:,2:]

array([[34, 29, 38],
       [44, 35, 15],
       [39, 45, 16],
       [36, 34,  9]])

In [ ]:
matrix[1:3, 1:3]

array([[45, 44],
       [22, 39]])

## Conditional Selecting

In [ ]:
arr1

array([45,  2,  3,  4, 28])

In [ ]:
arr1[0]

45

In [ ]:
arr1[1:4]

array([2, 3, 4])

In [ ]:
arr1[[True, False, False, True, False]]

array([45,  4])

In [ ]:
arr1 < 10

array([False,  True,  True,  True, False])

In [ ]:
arr1[arr1 < 10]

array([2, 3, 4])