<a href="https://colab.research.google.com/github/VivianeSouza923/HCIA_AI_HUAWEI_STUDY_if/blob/main/NumPy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**
* Support for large, multi-dimensional arrays
* Mathematical functions to operate on these arrays
* All the values are from the same type
* NumPy arrays use less memory than Python lists
---
## **Colab Shortcuts**
* **CTRL+Space**: Auto complete
* **CTRL+Shift+Space**: Documentation
* **CTRL+Enter**: Run current cell
* **Shift+Enter**: Run current cell and move focus to the next cell (adding one if none exists)
* **Alt+Enter**: Run current cell and insert a new cell below it.
---


## Creating Arrays

In [2]:
#importando a lib, óbvio
import numpy as np

In [3]:
#criar uma array passando a linha logo como parâmetro
# print arryay, só colocando o nome dela
array1 = np.array([2, 4, 1])
array1

array([2, 4, 1])

In [4]:
#quero saber o tipo da array
type(array1) # n-dimensional array

numpy.ndarray

In [5]:
# tipo?
type([2, 4, 1])

list

In [6]:
#criar uma array de 2 rows - dai você só separa as linhas (dentro de colchetes, óbvio) por vírgula ---> 
#np.array(([ar[linha1], [linha2]ray]))
matrix = np.array([[1, 4, 2], [7, 4, 2]])
#print (só colocar o nome e nada mais é obrigatório)
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [7]:
# tipo?
type(matrix)

numpy.ndarray

In [8]:
#mostra a linha 1 da matriz?
#nome_da_matriz[posição]
matrix[1]

array([7, 4, 2])

In [9]:
#quem está na posição 0 da linha 1?
#nome_da_matriz[posição da linha][posição da coluna]
matrix[1][0]

7

In [10]:
# mesma coisa da célula anterior, só que de outro jeitinho
matrix[1, 0]

7

In [11]:
# cria uma matriz através da arange (dai tu passa o ínicio e o fim como parâmetros, lembrando que começa em zero, logo o fim fica n-1)
# matrizNova = np.arange(initial_position, final_position)
array2 = np.arange(1, 10) # array range
#print
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# cria uma array de 5 a 54, espaçado de 5
#np.arange(initial_position, final_position, espaçamento)
np.arange(5, 54, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [13]:
#mesma lógica da célula anterior
np.arange(1, 10, 3)

array([1, 4, 7])

In [14]:
#matriz de zeros: 
#matriz_zeros = np.zeros(quantidade)
zeros1d = np.zeros(5)
#print
zeros1d

array([0., 0., 0., 0., 0.])

In [15]:
#matriz de zeros de 2 dimensões
#np.zeros((x,y)) ou np.zeros([x,y])
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#matriz de 1's
#siga a mesma lógica da matriz de zeros
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
#matriz de zeros de 2 dimensões
#siga a mesma lógica da matriz de zeros
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# cria uma matriz identidade
#np.eye(ordem)
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
# vai retornar 5 números, EQUIESPAÇADOS, de 1 a 10.
#np.linspace(initial_position, final_position, quantidade_de_elementos)
arr1 = np.linspace(1, 10, 5)
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
# mais um exemplo:
np.linspace(1, 11, 7)

array([ 1.        ,  2.66666667,  4.33333333,  6.        ,  7.66666667,
        9.33333333, 11.        ])

In [21]:
#criação de array:
#np.random.rand(quantidade de elementos)
#rand - números aleatórios entre 0 e 1 (0 - inclusivo e 1 - exclusivo)
np.random.rand(5)

array([0.30267568, 0.12337835, 0.66339989, 0.24639248, 0.84752897])

In [22]:
# np.random.rand(linha, coluna) - criação de array
random_array = np.random.rand(2, 3)
# print
random_array

array([[0.63303726, 0.06864025, 0.80319689],
       [0.51929175, 0.4763114 , 0.16248086]])

In [23]:
#Distribuição normal padrão com média zero e desvio padrão igual a um, isso quer dizer que terá também números negativos
np.random.randn(4)

array([-0.14190049, -0.03041292, -1.03522211, -1.52529057])

In [24]:
# faz um sorteio de acordo com os parâmetros passados
# o número sorteado vai ser dentro do grupo de 2 a 50 - número aleatório será sorteado
np.random.randint(2, 50)

35

In [25]:
#criando uma matriz aleatória através do randint
#np.random.randint(inicio, fim, (shape))
np.random.randint(2, 50, (4, 2))

array([[31, 31],
       [45, 18],
       [19, 40],
       [15,  5]])

In [26]:
# shape da arr1
arr1.shape

(5,)

In [27]:
# shape da matrix
matrix.shape

(2, 3)

In [28]:
# print
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [29]:
#a matriz era (2,3), lembra? então, 3*2=2*3=6, logo tem a mesma quantidade de elementos
matrix.reshape(3, 2) # tem que ter a mesma quantidade de elementos

array([[1, 4],
       [2, 7],
       [4, 2]])

## Operations

In [30]:
# print
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
# qual o maior número dentro da array?
arr1.max()

10.0

In [32]:
# qual a posição do maior número dentro da array?
arr1.argmax()

4

In [33]:
# média dos números dentro da array?

arr1.mean()

5.5

In [34]:
# array + 2, se estudou álgebra, sabe que cada elemento dessa array será acrescido em 2
arr1 + 2

array([ 3.  ,  5.25,  7.5 ,  9.75, 12.  ])

In [35]:
#array * 3, se estudou álgebra, sabe que cada elemento dessa array será multiplicado por 3
arr1 * 3

array([ 3.  ,  9.75, 16.5 , 23.25, 30.  ])

In [36]:
#  5 números aleatórios entre 2 e 50 serão sorteados para montar uma array
arr1 = np.random.randint(2, 50, 5)

In [37]:
# mesma lógica da célula anterior, só que com números diferentes
arr2 = np.random.randint(5, 60, 5)

In [38]:
#print
arr1

array([11, 31, 22, 21,  3])

In [39]:
#print
arr2

array([54, 18, 18, 48, 37])

In [40]:
# multiplicação de arrays
arr1 * arr2

array([ 594,  558,  396, 1008,  111])

In [41]:
# quadrado da array:
arr1 ** 2

array([121, 961, 484, 441,   9])

In [42]:
#raiz quadrada da array
np.sqrt(arr1)

array([3.31662479, 5.56776436, 4.69041576, 4.58257569, 1.73205081])

In [43]:
# soma dos elementos da array
np.sum(arr1)

88

In [44]:
# print
matrix

array([[1, 4, 2],
       [7, 4, 2]])

In [45]:
# montando uma array passando todos os elementos, separados por linhas já
matrix2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]])
# print
matrix2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [47]:
# shape da matriz
matrix.shape

(2, 3)

In [48]:
# shape da matriz
matrix2.shape

(3, 4)

In [49]:
# multiplicação de matrizes
result = np.matmul(matrix, matrix2)
# print
result

array([[19, 26, 33, 40],
       [25, 38, 51, 64]])

In [50]:
# shape da matriz
result.shape

(2, 4)

In [51]:
# criação de matriz aleatória, através de sorteio (entre 1 e 100), com o shape (4,5)
arr2d = np.random.randint(1, 100, (4, 5))
# print
arr2d

array([[52, 46, 82, 80, 46],
       [67, 80,  6, 39, 14],
       [ 8, 45, 16, 99, 45],
       [55,  4, 93, 51, 35]])

In [52]:
# soma dos elementos da matriz
arr2d.sum()

963

In [53]:
# soma das linhas da matriz
arr2d.sum(axis=0)

array([182, 175, 197, 269, 140])

In [55]:
# soma das colunas da matriz
arr2d.sum(axis=1)

array([306, 206, 213, 238])

## Slices

In [57]:
# print
arr1

array([11, 31, 22, 21,  3])

In [59]:
# fatiamento, pego de position 1 a 4 da matriz (o 4 não é inclusivo)
arr1[1:4]

array([31, 22, 21])

In [61]:
# aqui eu estou atribuindo 20 A TODOS OS NÚMEROS de 1 a 4
arr1[1:4] = 20

In [62]:
# print
arr1

array([11, 20, 20, 20,  3])

In [63]:
# vou atribuir uma arange de 2 a 5, lembrando que o 5 não é inclusivo, a arr1[1:4], ou seja, todos os números de 1 a 4 da arr1 irão ser mudados assim.  (lembrando que o 4 não é inclusivo)

arr1[1:4] = np.arange(2, 5)
# print
arr1

array([11,  2,  3,  4,  3])

In [64]:
# criação de matriz aleatória (random), de 1 a 50 (randint), com o shape(4,5)
matrix = np.random.randint(1, 50, (4, 5))
# print
matrix

array([[34, 23,  3, 21, 18],
       [28, 36, 19, 23, 36],
       [ 4, 30,  2, 26, 14],
       [22, 32, 48, 10, 24]])

In [ ]:
# continuar
matrix[:,2:]

array([[34, 29, 38],
       [44, 35, 15],
       [39, 45, 16],
       [36, 34,  9]])

In [ ]:
matrix[1:3, 1:3]

array([[45, 44],
       [22, 39]])

## Conditional Selecting

In [ ]:
arr1

array([45,  2,  3,  4, 28])

In [ ]:
arr1[0]

45

In [ ]:
arr1[1:4]

array([2, 3, 4])

In [ ]:
arr1[[True, False, False, True, False]]

array([45,  4])

In [ ]:
arr1 < 10

array([False,  True,  True,  True, False])

In [ ]:
arr1[arr1 < 10]

array([2, 3, 4])